services:
  # backend
  savingstracker_backend:
    container_name: savingstracker_backend
    build:
      context: savingsTacker/
      dockerfile: Dockerfile
    ports:
      - 5432:80

  # frontend
  savingstracker_frontend:
    container_name: savingstracker_backend
    build:
      context: .
      dockerfile: savingsTacker/ClientApp/Dockerfile
    ports:
      - 5431:3000
    environment:
      - BROWSER=none
      - ASPNETCORE_HTTPS_PORT=443
      - ASPNETCORE_URLS="http://localhost:5432"
    depends_on:
      - savingstracker_backend